### ISSUE TITLE
Validate ISRC country code correctly

### ISSUE THREAD

**Issue by Bernardo-MG** [weso/CWR-DataApi#65]
The country code on the ISRC follows the ISO 3166-1-Alpha-2 standard, and should be validated against it.

Currently it is not doing so.

**Comment by Alexkane** [comment]
In addition to the ISO country codes the following codes are also valid:

QR,CP,DG,ZZ

**Comment by Bernardo-MG** [comment]
The version in the development branch now validates ISRC country codes, including the four special codes.
